name: server-container

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Build and Publish latest Docker image
        uses: TCPShield/gp-docker-action@1.1.13
        with:
            github-token: ${{ secrets.TOKEN_GITHUB }} # Provide GITHUB_TOKEN to login into the GitHub Packages
            image-name: dcsmanagement # Provide only Docker image name, tag will be automatically set to latest
